name: Install SDL2 (MSYS2 / MinGW)
runs:
  using: composite
  steps:
    - name: Install MSYS2 + MinGW packages (both arches)
      if: ${{ runner.os == 'Windows' }}
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >
          mingw-w64-x86_64-SDL2
          mingw-w64-i686-SDL2
          mingw-w64-x86_64-pkg-config
          mingw-w64-i686-pkg-config
          mingw-w64-x86_64-toolchain
          mingw-w64-i686-toolchain

    - name: Locate msys2 pkg-config, create wrapper, export PATH & PKG_CONFIG_PATH
      if: ${{ runner.os == 'Windows' }}
      shell: powershell
      run: |
        Write-Host "Searching for mingw pkg-config.exe under RUNNER_TEMP..."
        $found = Get-ChildItem -Path $env:RUNNER_TEMP -Filter 'pkg-config.exe' -Recurse -ErrorAction SilentlyContinue |
                 Where-Object { $_.FullName -match 'mingw(64|32)\\bin' } |
                 Select-Object -First 1

        if (-not $found) {
          Write-Host "Not found under RUNNER_TEMP; checking C:\msys64\mingw64\bin\pkg-config.exe"
          $fallback = 'C:\msys64\mingw64\bin\pkg-config.exe'
          if (Test-Path $fallback) {
            $found = Get-Item $fallback
          }
        }

        if (-not $found) {
          Write-Error "Could not locate mingw pkg-config.exe. Dumping top level of RUNNER_TEMP for debugging:"
          Get-ChildItem -Path $env:RUNNER_TEMP -Directory -ErrorAction SilentlyContinue | Select-Object FullName,Name | Format-Table -AutoSize
          exit 1
        }

        $pkgExe = $found.FullName
        Write-Host "Found pkg-config at: $pkgExe"

        $wrapperDir = Join-Path $env:RUNNER_TEMP 'pkg-config-wrapper'
        New-Item -ItemType Directory -Path $wrapperDir -Force | Out-Null

        $wrapperPath = Join-Path $wrapperDir 'pkg-config.cmd'
        $content = "@echo off`r`n`"$pkgExe`" %*"
        Set-Content -Path $wrapperPath -Value $content -Encoding ASCII

        Write-Host "Wrapper created at: $wrapperPath"

        # Make wrapper directory first on PATH for subsequent steps
        Add-Content -Path $env:GITHUB_PATH -Value $wrapperDir

        # Derive pkgconfig directories from discovered pkg-config location
        $binDir = Split-Path -Parent $pkgExe            # ...\mingw64\bin
        $rootDir = Split-Path -Parent $binDir           # ...\mingw64
        $pkgconf64 = Join-Path $rootDir 'lib\pkgconfig'
        $pkgconf32 = $pkgconf64 -replace 'mingw64','mingw32'
        $pkgPaths = "$pkgconf64;$pkgconf32"

        Write-Host "Setting PKG_CONFIG_PATH to: $pkgPaths"
        Add-Content -Path $env:GITHUB_ENV -Value ("PKG_CONFIG_PATH=" + $pkgPaths)

    - name: Quick verification (uses wrapper)
      if: ${{ runner.os == 'Windows' }}
      shell: powershell
      run: |
        Write-Host "Which pkg-config will be used (should be wrapper):"
        Get-Command pkg-config -ErrorAction SilentlyContinue | Format-List Path,Version

        Write-Host "pkg-config --modversion sdl2"
        try {
          pkg-config --modversion sdl2
        } catch {
          Write-Error "pkg-config failed to find sdl2: $($_.Exception.Message)"
          Write-Host "PKG_CONFIG_PATH = $env:PKG_CONFIG_PATH"
          exit 1
        }