name: Install SDL2 (MSYS2 / MinGW)
runs:
  using: "composite"
  steps:
    - name: Install MSYS2 + MinGW packages (both arches)
      if: ${{ runner.os == 'Windows' }}
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >
          mingw-w64-x86_64-SDL2
          mingw-w64-i686-SDL2
          mingw-w64-x86_64-pkg-config
          mingw-w64-i686-pkg-config
          mingw-w64-x86_64-toolchain
          mingw-w64-i686-toolchain
        location: C:\msys64

    - name: Create pkg-config wrapper and export env
      if: ${{ runner.os == 'Windows' }}
      shell: powershell
      run: |
        $wrapperDir = 'C:\pkg-config'
        New-Item -ItemType Directory -Path $wrapperDir -Force | Out-Null

        $msysPkg = 'C:\msys64\mingw64\bin\pkg-config.exe'
        if (-not (Test-Path $msysPkg)) {
          Write-Error "Expected pkg-config at $msysPkg but it was not found."
          exit 1
        }

        $wrapperPath = Join-Path $wrapperDir 'pkg-config.cmd'
        $content = "@echo off`r`n`"$msysPkg`" %*"
        Set-Content -Path $wrapperPath -Value $content -Encoding ASCII

        # Make the wrapper directory first on PATH for subsequent steps
        Add-Content -Path $env:GITHUB_PATH -Value $wrapperDir

        # Ensure pkg-config can find .pc files from MSYS2
        $pkgPaths = 'C:\msys64\mingw64\lib\pkgconfig;C:\msys64\mingw32\lib\pkgconfig'
        Add-Content -Path $env:GITHUB_ENV -Value ("PKG_CONFIG_PATH=" + $pkgPaths)

    - name: Quick verification
      if: ${{ runner.os == 'Windows' }}
      shell: powershell
      run: |
        Write-Host "Which pkg-config will be used (should be our wrapper):"
        Get-Command pkg-config -ErrorAction SilentlyContinue | Format-List Path,Version

        Write-Host "pkg-config --modversion sdl2"
        try {
          pkg-config --modversion sdl2
        } catch {
          Write-Error "pkg-config failed: $($_.Exception.Message)"
          exit 1
        }