runs:
  using: composite
  steps:
    - name: Install MSYS2 + MinGW packages (both arches)
      if: ${{ runner.os == 'Windows' }}
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >
          mingw-w64-x86_64-SDL2
          mingw-w64-i686-SDL2
          mingw-w64-x86_64-pkg-config
          mingw-w64-i686-pkg-config
          mingw-w64-x86_64-toolchain
          mingw-w64-i686-toolchain
        # install in the well-known location so subsequent steps can rely on it
        location: C:\msys64

    - name: Export MinGW bins and PKG_CONFIG_PATH for later steps
      if: ${{ runner.os == 'Windows' }}
      shell: bash
      run: |
        # Make MSYS2's mingw bins available to later steps (added to PATH)
        echo "C:\msys64\mingw64\bin" >> $GITHUB_PATH
        echo "C:\msys64\mingw32\bin" >> $GITHUB_PATH

        # Tell pkg-config where to find .pc files
        echo "PKG_CONFIG_PATH=C:\msys64\mingw64\lib\pkgconfig;C:\msys64\mingw32\lib\pkgconfig" >> $GITHUB_ENV

    - name: Quick verification (PowerShell)
      if: ${{ runner.os == 'Windows' }}
      shell: powershell
      run: |
        # Ensure current step sees the new bins immediately
        $env:PATH = "C:\msys64\mingw64\bin;C:\msys64\mingw32\bin;" + $env:PATH
        Write-Host "pkg-config resolved to:"
        Get-Command pkg-config -ErrorAction SilentlyContinue | Format-List Path,Version
        Write-Host "SDL2 pkg version (pkg-config --modversion sdl2):"
        pkg-config --modversion sdl2