name: Install SDL2 (MSYS2 / MinGW)
description: Install SDL2 for MINGW32 and MINGW64 on Windows runners (msys2/setup-msys2).
runs:
  using: "composite"
  steps:
    - name: Install SDL2 (MINGW64)
      if: ${{ runner.os == 'Windows' }}
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >
          mingw-w64-x86_64-SDL2
          mingw-w64-x86_64-pkg-config
          mingw-w64-x86_64-toolchain

    - name: Install SDL2 (MINGW32)
      if: ${{ runner.os == 'Windows' }}
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW32
        update: false
        install: >
          mingw-w64-i686-SDL2
          mingw-w64-i686-pkg-config
          mingw-w64-i686-toolchain

    - name: Add MinGW bin dirs to PATH
      if: ${{ runner.os == 'Windows' }}
      shell: bash
      run: |
        echo "C:\msys64\mingw64\bin" >> $GITHUB_PATH
        echo "C:\msys64\mingw32\bin" >> $GITHUB_PATH

    - name: Verify SDL2 (pkg-config)
      if: ${{ runner.os == 'Windows' }}
      shell: powershell
      run: |
        & 'C:\msys64\mingw64\bin\pkg-config.exe' --modversion sdl2
        & 'C:\msys64\mingw32\bin\pkg-config.exe' --modversion sdl2