runs:
  using: "composite"
  steps:
    - name: Install MSYS2 + MinGW packages (both arches)
      if: ${{ runner.os == 'Windows' }}
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >
          mingw-w64-x86_64-SDL2
          mingw-w64-i686-SDL2
          mingw-w64-x86_64-pkg-config
          mingw-w64-i686-pkg-config
          mingw-w64-x86_64-toolchain
          mingw-w64-i686-toolchain

    - name: Add MinGW bin dirs to PATH
      if: ${{ runner.os == 'Windows' }}
      shell: bash
      run: |
        echo "C:\msys64\mingw64\bin" >> $GITHUB_PATH
        echo "C:\msys64\mingw32\bin" >> $GITHUB_PATH

    - name: Verify SDL2 pkg-config (PowerShell)
      if: ${{ runner.os == 'Windows' }}
      shell: powershell
      run: |
        Write-Host "MINGW64 pkg-config sdl2:"
        & 'C:\msys64\mingw64\bin\pkg-config.exe' --modversion sdl2
        Write-Host "MINGW32 pkg-config sdl2:"
        & 'C:\msys64\mingw32\bin\pkg-config.exe' --modversion sdl2